[package]
name = "world-wiki"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
colored = "2.1.0"
pulldown-cmark = "0.11.0"
tokio = { version = "1.39.2", features = ["full"] }
tracing = "0.1.40"
